# Generated by Django 3.1.2 on 2020-11-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartUS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensordata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Articulos',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
